### ISSUE TITLE
M1 CHILDSUM inconsistent on dev

### ISSUE THREAD

**Issue by okisahia** [episphere/questionnaire#390] opened 2024-07-17 21:29 UTC
We're seeing something weird with the CHILDMULT summary within CHILDSUM and want to see if this is a Quest or PWA issue. 

In summary, testing on dev, Nacido como mellizo, trillizo o de un parto múltiple:" shows up sometimes and is not always accurate. These issues were not found when testing with the renderer.

Here are the details of the last couple of tests on dev:
**laptop + chrome using questtest39 (1691226813)** Follows scenario 2
-loops 1 and 2: CHILDMULT = NR, "Nacido como mellizo, trillizo o de un parto múltiple:" does not show up in CHILDSUM. This is expected.
- When CHILDMULT = No, the sentence still did not show up in the summary (this is not the expected behavior). The same result is seen when CHILDMULT = Si (for the 4th sibling).
![image](https://github.com/user-attachments/assets/d56548eb-ea3f-45d9-80e6-263d3bf7e0e3)

**laptop + firefox. questtest40 (9937359264)**
- loop 1: CHILDMULT = NR, CHILDCANC = yes. "Nacido como mellizo, trillizo o de un parto múltiple:" was not listed in the summary. This is expected.
![image](https://github.com/user-attachments/assets/a087607e-23aa-4d2f-9e94-ed0bdb5e759a)

- loop2: CHILDMULT = NR, CHILDCANC = yes. "Nacido como mellizo, trillizo o de un parto múltiple:" was listed in CHILDSUM. as "No". tried this 2x with the same result.
![image](https://github.com/user-attachments/assets/3b45b9ac-f7b7-41a7-a74c-851399ef1cdc)
![image](https://github.com/user-attachments/assets/a6080154-f073-41d4-9ddc-54f333ef1612)

-loop3: CHILDMULT = No, CHILDCANC = Yes. The summary is listed as expected
![image](https://github.com/user-attachments/assets/8f0c4e97-4416-4229-a6b2-58d54189fa32)

It's puzzling why we are getting different results with each test.

**Comment by anthonypetersen** [comment] 2024-07-18 13:32
@okisahia does this same issue happen if you run this scenario in English?

**Comment by cusackjm** [comment] 2024-07-18 14:34
I was not able to replicate this in Spanish using chrome on a PC. Did you test this after I pushed Module 1 on 7/17 at 9:45? Wondering if this was on an old version of the markdown?

**Comment by cusackjm** [comment] 2024-07-18 14:53
Also did not reproduce on firefox @okisahia can you confirm when this was tested

**Comment by okisahia** [comment] 2024-07-18 15:06
This was testing was done 7/17 after 9:45a

**Comment by okisahia** [comment] 2024-07-18 15:09
Well, the 1st test (laptop +chrome) was triggered around that time, but the laptop + mozilla test was started in the afternoon.

**Comment by okisahia** [comment] 2024-07-18 15:48
Sure, I'll send you call invite.

**Comment by okisahia** [comment] 2024-07-18 16:33
![image](https://github.com/user-attachments/assets/1cc95c96-b263-4cd5-9f57-64d18f71d250)

@anthonypetersen Is this useful?

**Comment by okisahia** [comment] 2024-07-18 16:36
> @okisahia does this same issue happen if you run this scenario in English?

We didn't test in English.

**Comment by anthonypetersen** [comment] 2024-07-18 17:58
@okisahia not particularly - can you reproduce this issue using the PWA instead of the renderer?

**Comment by okisahia** [comment] 2024-07-18 18:20
This above testing was done in PWA

**Comment by boyd-mj** [comment] 2024-07-24 19:21
@cusackjm according to our team, this issue wasn't reproduceable and this section of code has since passed testing. They recall a discussion with you that it was probably related to a version update so I think we can close this.

**Closed** 2024-07-24 19:26 UTC
Labels: Mod1
