### ISSUE TITLE
PREWORKT7 grid showing incorrect responses

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#131] opened 2022-06-09 20:30 UTC
Similar issue to CURWORK happening in PREWORK (#130)

PREWORKT1 - 1 "commuter rail, subway, metro"
PREWORKT4 - 0 "No"
PREWORKT5 - correctly skipped due to logic
PREWORKT6 - 1 "Taxicab"

Seeing both "commuter rail" and "taxicab" in PREWORKT7 grid, but shouldn't based on the first line of instructions in PREWORKT7

Issue likely do to the "If PREWORKT5 = NO, then display rows marked in PREWORKT1"

![Screen Shot 2022-06-09 at 4 18 19 PM](https://user-images.githubusercontent.com/83971268/172936688-d592a13f-9b12-4782-85df-c73c8faf46f0.png)

**Comment by FrogGirl1123** [comment] 2022-06-10 13:01
@boyd-mj Hi Jen, do you have an update on this issue this morning?

**Comment by boyd-mj** [comment] 2022-06-10 14:35
This issue has been fixed and will be included in the next delivery

**Comment by cusackjm** [comment] 2022-06-10 15:57
@huip-ims qx document is updated

**Comment by cusackjm** [comment] 2022-06-13 13:34
@huip-ims @boyd-mj hi what is the status on this

**Comment by boyd-mj** [comment] 2022-06-13 14:04
Hi Julie, per my comment above the issue is fixed and will be included when we redeliver M4.

**Comment by cusackjm** [comment] 2022-06-13 17:28
tested and fixed on 6/13

**Closed** 2022-06-13 17:28 UTC
Labels: Mod4, MVP, RE-TEST THE FIX
