### ISSUE TITLE
Issues in Module 1 Scenario #3 Spanish

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#369] opened 2024-06-13 18:54 UTC
1. For OCCUPTN1 and 2, the Connect screen has "Identifique la categoría laboral que mejor describa este trabajo." which doesn't match Qx Word doc. This may be an NCI issue, since this question is coming from outside of Quest.

2. For ALTADDRESS2, testing scenario instructs to move forward without answering this question. However, the markdown has "Línea 1", "Ciudad" and Zip as required, so I can’t move forward to finish testing the questionnaire. Are these still required fields? Either the testing scenario instruction or the markdown is wrong. Document has * next to them. Does that mean they are required?

**Comment by cusackjm** [comment] 2024-06-13 19:31
1. OCCUPTN 1 and 2 are piped in from SOCcer, so I assume we will have to use their translation @m-j-horner can you confirm?
2. ALTADDRESS2 should not be required

**Comment by anthonypetersen** [comment] 2024-06-13 19:48
1. This doesn't come from SOCcer technically, it comes from the PWA. That is the translation that was given to us from NORC I believe.

**Comment by joshid-ims** [comment] 2024-06-13 19:49
ALTADDRESS2 as a question is not required but are some of the text boxes/values under ALTADDRESS2 required? what are the * characters in the document next to Line1, City and Zip?

**Comment by cusackjm** [comment] 2024-06-13 20:04
Not sure why they are there, they don't appear to have a significance in the qx doc

**Comment by joshid-ims** [comment] 2024-06-13 20:20
Should we make these Line1, City not required? They are required in code. In English too.

**Comment by cusackjm** [comment] 2024-06-14 13:27
yes, they should not be required

**Comment by huip-ims** [comment] 2024-07-16 20:37
@cusackjm Julie-Circling back to OCCUPTN1 and 2. Since the translation comes from PWA, do you just want to update the Word doc to match the PWA? Currently, here's the text discrepancy between the Word doc and MyConnect in Dev. See highlighted yellow and red in screenshot.

![image](https://github.com/user-attachments/assets/e4678053-c403-4e21-a3ef-ef73c81e6240)

**Comment by cusackjm** [comment] 2024-07-17 13:49
I will update Qx Doc

**Comment by huip-ims** [comment] 2024-07-18 20:00
Confirmed - OCCUPTN1 & OCCUPTN2 in Qx Doc have been updated to match SOCcer in Dev.

**Comment by guinevere83** [comment] 2024-07-22 14:06
All other issues except for OCCUPTN2 are fixed:

![image](https://github.com/user-attachments/assets/5dbb3295-4e7b-48fc-a9a8-32f9803f515f)

![image](https://github.com/user-attachments/assets/4cf75e90-68b2-4f13-b622-a37d626541cb)

**Comment by woodruffr** [comment] 2024-07-22 17:34
This is confirmed fixed in Dev Testing.

**Closed** 2024-07-23 17:04 UTC
Labels: Mod1, Prod Push- JULY 24
