### ISSUE TITLE
Biospecimen - time last ate Mobile issue

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/questionnaire#276] opened 2023-08-02 20:42 UTC
Putting this here for our team to look into. 

Participant was completing their biospecimen survey in clinic using an Android phone and Google Chrome browser. When they got to the question pertaining to the last time they ate, they were unable to submit the time. They could select that it was 11:40 am, however the only options were clear or cancel, there was no option to submit that data. To troubleshoot, our team member suggested that the participant change their login method to a phone number and login on one of our study iPads. They were then able to successfully submit the time information and continue on to complete the survey

**Comment by cusackjm** [comment] 2023-08-03 15:06
I will try to replicate the issue on an Android once my Android MobileIron is updated

**Comment by cusackjm** [comment] 2023-08-04 12:48
The box is not grey and does appear blank, but if you tap on the box, the clock will pop up. (note it is in a different format, the ipad/iphone is a scrolling drop down)
![image](https://github.com/episphere/questionnaire/assets/85582895/0f7dd4df-b8a9-4784-9fd5-f096cb594772)
![image](https://github.com/episphere/questionnaire/assets/85582895/d720408f-c3f4-4cf7-bf08-dd18cf7fad30)
![image](https://github.com/episphere/questionnaire/assets/85582895/ac8826eb-5b6d-4e09-9077-7c130d86aa4d)

**Comment by cusackjm** [comment] 2023-08-04 12:53
@danielruss do you know if the time entry was always an analog clock for Androids? I do not recall ever seeing this format, but I just updated the Android and wonder if it is part of the update

**Comment by danielruss** [comment] 2023-08-04 13:02
@cusackjm This format looks familiar to me.  I haven't used the time input on android very often, but I can check on my cell phone.

**Comment by danielruss** [comment] 2023-08-04 16:15
The participant could also click the keyboard icon visible to the left of set/cancle/clear

**Comment by danielruss** [comment] 2023-08-04 16:16
I cannot reproduce the error.

**Comment by Davinkjohnson** [comment] 2023-08-04 16:50
@danielruss or @cusackjm Could you try changing the size of the text (like in the phone settings) as an example of how a participant with diminished vision may have on their phone?

**Comment by cusackjm** [comment] 2023-08-09 13:42
I changed the font, made it bigger, and bold, but none of those changes impacted the font in the PWA dashboard (the bottom banner text did change)

**Comment by cusackjm** [comment] 2023-11-06 15:12
I believe this may have been a confused participant? Is it ok to close this issue (closed as not planned)?

**Comment by brotzmanmj** [comment] 2023-11-06 15:31
If we've confirmed that the calendar selection works on both iPhone and Android phones then I agree we can close it.

We should give guidance to NORC so they can assist participants who have questions about this. @cusackjm did we already do that for this case?

If it reoccurs we can open a new issue.

**Comment by cusackjm** [comment] 2023-11-06 15:48
@brotzmanmj yes, I've confirmed it works. My best guess is they didn't know to tap on the clock to change the time, although we explicitly state in the question text to tap the box to enter a time. Does NORC need guidance for this?

**Comment by brotzmanmj** [comment] 2023-11-06 15:50
Yes, I assume the CSC case on this one is long since closed, but please email NORC to request that they make sure their agents are aware of this.

**Closed** 2023-11-06 15:54 UTC
Labels: blood urine, CSC
