### ISSUE TITLE
[CIG10] & [CIG11] Wording of question error in PWA

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#116] opened 2022-05-23 21:04 UTC
Response at [CIG5] = 0 "In the past month"

[CIG11] in the PWA

<img width="540" alt="Screen Shot 2022-05-23 at 4 58 25 PM" src="https://user-images.githubusercontent.com/83971268/169905080-951de512-8d11-4c57-984d-b9b56635453c.png">

Based on the specs document, the question should read:

<img width="634" alt="Screen Shot 2022-05-23 at 4 59 01 PM" src="https://user-images.githubusercontent.com/83971268/169905168-d3afe056-52ab-45d8-ad48-a91798e07984.png">

Tagging IMS and Brian - not sure if this is a Mark up, Quest, or PWA issue

**Comment by cunnaneaq** [comment] 2022-05-24 18:26
[CIG10] Similar issue with wording as above.  Not pulling "[do/did]" into the sentence.

PWA:
![Screen Shot 2022-05-24 at 2 24 32 PM](https://user-images.githubusercontent.com/83971268/170105880-596ff824-f49e-4b13-8e4e-5cf789d860b4.png)

Specs doc: 

![Screen Shot 2022-05-24 at 2 25 59 PM](https://user-images.githubusercontent.com/83971268/170106145-bb26bffe-4b8e-4bab-8026-bc38a01cb92e.png)

**Comment by joshid-ims** [comment] 2022-06-09 18:55
@cunnaneaq Is it a PWA issue? In markup, same logic is used to display current/past tense in other questions 10.

**Comment by naiyume** [comment] 2022-06-15 19:48
@joshid-ims 
```
[D_534351312?,displayif=equals(D_947205597,712653855)] On a usual day that you |displayif=and(doesNotEqual(D_798549704,484055234),doesNotEqual(D_798549704,802197176))| smoke||displayif=or(equals(D_798549704,484055234),equals(D_798549704,802197176))|smoked||displayif=equals(isDefined(D_798549704,317567178),0)| do||displayif=or(equals(D_798549704,484055234),equals(D_798549704,802197176))| did| you smoke a cigarette before your first meal of the day?
(122802180) Almost all the time
(950591599) Most of the time
(167208049) About half of the time
(793320798) Some of the time
(216450786) Almost never
```

This is the code that shows up for do/did

Shouldn't it look more like this?

```
[D_534351312?,displayif=equals(D_947205597,712653855)] On a usual day that you |displayif=and(doesNotEqual(D_798549704,484055234),doesNotEqual(D_798549704,802197176))| smoke||displayif=or(equals(D_798549704,484055234),equals(D_798549704,802197176))|smoked||displayif=equals(D_798549704,317567178)| do||displayif=or(equals(D_798549704,484055234),equals(D_798549704,802197176))| did| you smoke a cigarette before your first meal of the day?
(122802180) Almost all the time
(950591599) Most of the time
(167208049) About half of the time
(793320798) Some of the time
(216450786) Almost never
```

**Comment by cusackjm** [comment] 2022-06-23 13:30
@joshid-ims what is the status on this?

**Comment by cusackjm** [comment] 2022-07-06 20:59
@guinevere83 I replaced hookah10 with hookahlife and pipe10 with pipelife in the questionnaire documents

**Comment by cusackjm** [comment] 2022-07-25 16:15
issue still present for CIG10 and CIG11 in 7/25 testing 
![image](https://user-images.githubusercontent.com/85582895/180825736-5305fc09-b0c5-4f9e-99ff-0eb14d07262d.png)
![image](https://user-images.githubusercontent.com/85582895/180825838-41ef5def-7ba7-4f20-a49e-c3bd9a8b9508.png)

**Comment by cusackjm** [comment] 2022-07-27 18:10
The following scenarios will take a participant to CIG10 & CIG11

**Scenario1:**
CIG1= 3
CIG2= (enter anything)
CIG3= (enter anything)
CIG4= 0, 1, or 2
CIG5= 2
CIG8= (enter anything)
CIG8C= 1
CIG9A= (enter anything)
CIG10= (enter anything)
CIG11= (enter anything)

**Scenario2:**
CIG1= 3
CIG2= (enter anything)
CIG3= (enter anything)
CIG4= 3
CIG9A= (enter anything)
CIG10= (enter anything)
CIG11= (enter anything)

**Scenario3:**
CIG1= 2
CIG2= (enter anything)
CIG3= (enter anything)
CIG4= 0, 1, or 2
CIG5= 0
CIG6= (enter anything)
CIG9A= (enter anything)
CIG9B= 1
CIG9D= (enter anything)
CIG9C= (enter anything)
CIG10= (enter anything)
CIG11= (enter anything)

**Scenario4:**
CIG1= 2
CIG2= (enter anything)
CIG3= (enter anything)
CIG4= 0, 1, or 2
CIG5= 1
CIG7A= (enter anything)
CIG8C= 1
CIG9A= (enter anything)
CIG10= (enter anything)
CIG11= (enter anything)

@guinevere83

**Comment by boyd-mj** [comment] 2022-07-27 19:33
Per our call today, we suspect this is a Quest issue. @naiyume is investigating.

**Comment by joshid-ims** [comment] 2022-07-28 14:55
Gwen could not reproduce any of these scenarios. @cusackjm @danielruss

**Comment by danielruss** [comment] 2022-07-28 15:17
@cusackjm I simplified the problem to the module below [Just look at CIG5, remove displayif from questions, soft check, and jumps]. In all cases the CIG10/CIG11 work as coded. 

```
[CIG5] When was the <b>last</b> time you smoked cigarettes?
(0) In the past month 
(1) More than a month ago, but in the past year
(2) More than 1 year ago

[CIG10] On a usual day that you |displayif=doesNotExist("CIG5") or valueEquals("CIG5",0)| smoke||displayif=valueIsOneOf("CIG5",1,2)|smoked|, how soon after you |displayif=doesNotExist("CIG5") or valueEquals("CIG5",0)|wake up||displayif=valueIsOneOf("CIG5",1,2)|woke up| |displayif=doesNotExist("CIG5") or valueEquals("CIG5",0)|do||displayif=valueIsOneOf("CIG5",1,2)|did| you smoke your first cigarette of the day?
(0) 5 minutes or less
(1) 6 to 30 minutes
(2) 31 to 59 minutes
(3) 1 hour
(4) 2 hours or more

[CIG11] On a usual day that you |displayif=doesNotExist("CIG5") or valueEquals("CIG5",0)| smoke,||displayif=valueIsOneOf("CIG5",1,2)|smoked,| how often|displayif=doesNotExist("CIG5") or valueEquals("CIG5",0)| do||displayif=valueIsOneOf("CIG5",1,2)| did| you smoke a cigarette before your first meal of the day?
(0) Almost all the time
(1) Most of the time
(2) About half of the time
(3) Some of the time
(4) Almost never

[END] All done
```

**Comment by joshid-ims** [comment] 2022-07-28 15:35
@cusackjm, is this seen only in CIG questions? 

@danielrus, I see that there is no code change for CIG10 and CIG11 questions. Was the issue only because of the displayif within the question brackets in CIG5, CIG10 and CIG11 (displayif=equals(TOBACCO,0))?

**Comment by cusackjm** [comment] 2022-07-28 15:42
@joshid-ims this was for all of the product10/11 questions

**Comment by danielruss** [comment] 2022-07-28 15:50
@joshid-ims No, the displayif in the bracket only affects whether or not the QUESTION is displayed, not the text.  

@naiyume I actually went back and tested with the displayif's in the questions.  Really weird, the first question was displayed (it should not). However, if I added a question before it, the question disappeared.  It appears there is a subtle bug that always displays the first question.  However, this is not a Connect concern and questions CIG10/11 appear to be working properly.

@cusackjm I see CIG11, but no ECIG11, CIGAR11, CHEW11, HOOKAH10 or 11, or PIPE10 or 11 in  
https://github.com/cyrjeant/privatequest/blob/master/module3.txt

**Comment by joshid-ims** [comment] 2022-07-28 16:16
@danielruss, I understand that displayif is only to decide if the question is displayed or not. But then why would the code which decides what to display work correctly when it is removed?

**Comment by danielruss** [comment] 2022-07-28 16:17
@joshid-ims  I thought this was about "smoke" or "smoked" and "do" or "did".

**Comment by joshid-ims** [comment] 2022-07-28 16:40
Yes, that is why I did not understand why removing displayif=equals(TOBACCO,0) would make the code work for that.

**Comment by danielruss** [comment] 2022-07-28 16:42
@joshid-ims   I am saying that the code works as expected.

>  In all cases the CIG10/CIG11 work as coded.

**Comment by joshid-ims** [comment] 2022-07-28 16:43
Oh ok. Sorry, I misunderstood. Yes, even we could not reproduce it.

**Comment by joshid-ims** [comment] 2022-07-29 12:49
@cusackjm what is the next step? Will you testing again to confirm?

**Comment by cusackjm** [comment] 2022-07-29 13:46
@joshid-ims I can test again today

**Comment by cusackjm** [comment] 2022-07-29 14:00
@danielruss @joshid-ims 
I entered this:

Scenario1: mococancerstudy@yahoo.com in Stage
CIG1= 3
CIG2= (enter anything)
CIG3= (enter anything)
CIG4= 0, 1, or 2
CIG5= 2
CIG8= (enter anything)
CIG8C= 1
CIG9A= (enter anything)
CIG10= (enter anything)
CIG11= (enter anything)

and now I'm seeing this at CIG9A (which I didn't see as an issue before)
![image](https://user-images.githubusercontent.com/85582895/181776300-86657926-6bd4-4b7d-99f0-3199435b27cf.png)

CIG10:
![image](https://user-images.githubusercontent.com/85582895/181776429-95130841-7e02-4c1f-bf8c-0511c4520005.png)

CIG11:
![image](https://user-images.githubusercontent.com/85582895/181776489-41613afd-5c04-4634-913e-18991e2f5f2a.png)

**Comment by danielruss** [comment] 2022-07-29 15:26
hmm.. ok I'll run the entire module through Quest, if that works.  I may need your help testing through the PWA.

**Comment by guinevere83** [comment] 2022-07-29 17:46
Hmm, I tried the module converted and unconverted in our renderer and the verbs were displaying. I wonder if we have a renderer difference potentially?

**Comment by danielruss** [comment] 2022-07-29 17:48
@guinevere83 what renderer are you referring to?

**Comment by guinevere83** [comment] 2022-07-29 17:51
I use the renderer here: https://episphere.github.io/quest/

**Comment by boyd-mj** [comment] 2022-08-04 16:57
@danielruss just making sure this is on your radar

**Comment by danielruss** [comment] 2022-08-04 22:34
@boyd-mj I cannot reproduce the error in quest.  I'll try to run it through the PWA.

**Comment by cusackjm** [comment] 2022-08-05 16:41
@danielruss @boyd-mj this is fixed in Dev testing. Was anything changed during the latest delivery? It was previously an issue in Stage

**Comment by danielruss** [comment] 2022-08-05 16:55
@cusackjm This is not a quest issue. I'm trying to check the PWA, but I cannot access it because of the SSL error on stage. This is a tough nut to crack for the IMS team and me, because we cannot reproduce the error.  As soon as stage comes online, I'll run it through the PWA.

**Comment by boyd-mj** [comment] 2022-08-05 20:56
> @danielruss @boyd-mj this is fixed in Dev testing. Was anything changed during the latest delivery? It was previously an issue in Stage

@cusackjm  I'm not sure which versions you are comparing. We've likely changed other things, but nothing specific to this issue. Your best bet would be to see what changed using the deliverables log: https://app.box.com/file/895785486944

**Comment by danielruss** [comment] 2022-08-05 20:58
sorry is it working now?

**Comment by cusackjm** [comment] 2022-08-08 13:05
@boyd-mj @danielruss Stage was down last week so I tested the latest delivery in Dev. I didn't see that this was fixed, but was confused to see that it was working as intended in Dev. Once Stage is working, I will test this again there

**Comment by cusackjm** [comment] 2022-08-12 12:57
Confirmed fixed in stage testing on 8/12

**Closed by cusackjm** 2022-08-12 12:57 UTC
Labels: Mod3
