### ISSUE TITLE
Unable to move forward after answering "yes" or "yes, mostly" to [COV21]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#152] opened 2022-07-15 19:36 UTC
[COV21] 2 = Yes, mostly
 when I click next, the PWA is a blank screen and the console has an error message 

![Screen Shot 2022-07-15 at 3 32 01 PM](https://user-images.githubusercontent.com/83971268/179297975-8fd2cf5f-5a2e-4cb4-90f4-2cab728efde3.png)

@naiyume is working on this issue.

Note: When [COV22] is skipped due to skip pattern, able to move through the questionnaire with no issue

**Comment by naiyume** [comment] 2022-07-20 19:07
@boyd-mj There is a change needed for the markup for this issue.

All instances of required should be replaced with required=true
For example, 
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/27040828/180062457-59e94aa3-4354-4387-a9bc-fed1994d8445.png">
This should become
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/27040828/180062519-a74fc9b5-f950-4a29-8a01-ebe7d537300d.png">

**Comment by cusackjm** [comment] 2022-09-19 16:03
@boyd-mj @joshid-ims Could you look into this?

**Comment by boyd-mj** [comment] 2022-09-19 16:29
> @boyd-mj @joshid-ims Could you look into this?

I've asked our team to look into this

**Comment by joshid-ims** [comment] 2022-09-19 20:53
@danielruss, we are getting this error 

![image](https://user-images.githubusercontent.com/64986739/191114263-a2dcfdac-754d-4be7-8e09-bd6a85b13f1c.png)

![image](https://user-images.githubusercontent.com/64986739/191114373-974ca116-41fb-469b-a4ec-eabb4ce0a094.png)

Is _value function an issue?

**Comment by danielruss** [comment] 2022-09-19 20:55
I had to handle dates a little different (2022-03 is march 2022, not 2018) .  Let me look into this.

**Comment by danielruss** [comment] 2022-09-19 20:56
@joshid-ims  Did you switch over to the month picker?

**Comment by danielruss** [comment] 2022-09-19 21:08
Works for me.

**Comment by joshid-ims** [comment] 2022-09-19 21:14
Have you pushed month picker to prod? We have only tested the changes so far in from Word document. Have to make in code branch. 

Did you test the exact scenario that Julie tested? Our tester Gwen could reproduce for:

![image](https://user-images.githubusercontent.com/64986739/191117761-5a5aa120-cd58-4a04-9161-2df3641554cb.png)

**Comment by danielruss** [comment] 2022-09-19 21:32
The error is that the question is **D_366972678_1_1** not D_366972678_1 and **D_173502329_1_1** not. D_173502329_1

**Comment by joshid-ims** [comment] 2022-09-20 12:52
It is happening in non-converted code as well. Did you try in whole module code?

**Comment by danielruss** [comment] 2022-09-20 20:28
@joshid-ims I completed the entire biospecimen module.  I can rerun with exact response above

**Comment by joshid-ims** [comment] 2022-09-21 19:07
@danielruss which version of code are you using? Or where are you testing?

**Comment by danielruss** [comment] 2022-09-21 19:09
I tested in the quest development tool, using the modules in https://github.com/cyrjeant/privatequest

**Comment by cusackjm** [comment] 2022-10-14 15:01
this was fixed in testing. We did not close after the last testing round because we wanted to ensure that participants were able to move past this issue in Prod. Given that this was not linked to any active participant issues, I am closing it

**Closed by cusackjm** 2022-10-14 15:01 UTC
Labels: RE-TEST THE FIX, MARKUP ISSUE, blood urine, IN PROD
