### ISSUE TITLE
Participant entered COV1=0 and still saw COV3

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#252] opened 2023-07-19 14:08 UTC
Participant issue CS00097: App is asking for date I had COVID (COV3) before it will let me continue. I never had COVID & there is no option to skip or say that I didn't have it.

Kelsey checked backend data and saw:
COV1= 0 no
COV2= null
COV3= null

If COV1= 0, participant should go to COV23_SKIP not COV2 

@danielruss is this a Quest/PWA issue?

**Comment by danielruss** [comment] 2023-07-19 18:25
[when I run with the stage module](https://episphere.github.io/quest/#https://raw.githubusercontent.com/episphere/questionnaire/main/moduleCOVID19Stage.txt)

I go from:
```
1. SRVCOV_COVIDINTRO_V1R0 
2. D_494226443
3. SRVCOV_COV23_V1R0

results:
D_793330426 {"D_494226443":"104430631"}
``` 

This happens because the displayif on [COV23] stops it from displaying the question, so it goes to [SRVCOV_COV23_V1R0].

Same on [prod [](module](https://episphere.github.io/quest/#https://raw.githubusercontent.com/episphere/questionnaire/main/prod/moduleCOVID19.txt).)

I cannot reproduce the error.

**Comment by cusackjm** [comment] 2023-07-24 18:56
Could this be an issue with data not saving?

**Comment by Davinkjohnson** [comment] 2023-09-13 16:43
This has been tested and seems to now be resolved. closing.

**Closed by Davinkjohnson** 2023-09-13 16:43 UTC
Labels: CSC, COVID-19 Survey
