### ISSUE TITLE
[SECMLF] incorrect ranges from [AGE] in mod 1

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#119] opened 2022-05-24 19:04 UTC
In Mod 1, I responded 0=No at [AGECOR] when it asked if I was 59 (the age calculated based on DOB entered in the user profile 12/6/1962) and typed in that I was 50 at [AGE].

In Mod 3, for [SECMLF] section.  I saw, "age 50 to age 59"

![Screen Shot 2022-05-24 at 3 01 07 PM](https://user-images.githubusercontent.com/83971268/170112383-b72ceaab-7334-4406-a43c-14b8ffe61093.png)

**Comment by cunnaneaq** [comment] 2022-05-24 19:25
Same for [ALCLIFE] intro and ranges:

![Screen Shot 2022-05-24 at 3 23 14 PM](https://user-images.githubusercontent.com/83971268/170115941-77648781-f6ac-4525-926a-4c84e2f79393.png)

![Screen Shot 2022-05-24 at 3 24 23 PM](https://user-images.githubusercontent.com/83971268/170116103-28c3e60b-c33e-499f-aa8b-c58490e64dc3.png)

**Comment by cusackjm** [comment] 2022-05-25 13:24
@naiyume is this related to this issue: https://github.com/episphere/questionnaire/issues/115?

**Comment by boyd-mj** [comment] 2022-05-26 15:10
@cusackjm @naiyume we were unable to reproduce this issue in either version of the markup

**Comment by naiyume** [comment] 2022-05-31 14:06
@cusackjm a fix has been pushed to dev, please test this out when you have a chance.

**Comment by cusackjm** [comment] 2022-05-31 20:37
fixed in testing (tommytesterdcge@gmail.com) on 5/31

**Closed by cusackjm** 2022-05-31 20:37 UTC
Labels: Mod3, RE-TEST THE FIX, QUEST ISSUE
