### ISSUE TITLE
Text box option does not get stored if only text is entered without selecting radio button

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#242] opened 2023-07-13 19:06 UTC
Found while testing https://github.com/episphere/questionnaire/issues/240. 

Saw this in COV28 and COV19C6A and COV28. Options 1 and 55, respectively, do not get stored in the Question ID if only text is entered in the text box without selecting the radio button for the option. The text gets stored in the corresponding variable though. 

Is this a Quest issue?

**Comment by Davinkjohnson** [comment] 2023-07-13 20:51
@joshid-ims isn't this basically the same issue as Julie describes in the 2nd comment on https://github.com/episphere/questionnaire/issues/240 ??

**Comment by joshid-ims** [comment] 2023-07-14 12:33
These were not text boxes in multi-choice questions. And I tried using the code Daniel suggested. But I will take a look again.

**Comment by joshid-ims** [comment] 2023-07-14 17:45
One effect of this is that when we select a value that isn't Other and then enter a value into the textbox, it displays both values, in spite of them being radio buttons. This is because the radio button option does not get saved but the text does along with value other than Other selected first. It does not get overwritten by Other option value. 

I think this is a Quest issue, right?

**Comment by joshid-ims** [comment] 2023-07-14 20:28
@danielruss and @cusackjm we have tested other issues internally and waiting for this.

**Comment by danielruss** [comment] 2023-07-17 14:01
@cusackjm  looking into it...

**Comment by danielruss** [comment] 2023-07-17 14:16
@joshid-ims @cusackjm   

> when we select a value that isn't Other and then enter a value into the textbox, it displays both values, in spite of them being radio buttons.

That should not happen.  I was able reproduced your error.  This is a quest issue.  Closing this issue and opening a quest issue.

**Comment by danielruss** [comment] 2023-07-17 15:25
@cusackjm @joshid-ims   Update is online, but not yet released.  You can use the dev tool to test.  If it looks good, I'll release.

**Comment by boyd-mj** [comment] 2023-07-18 20:17
> @cusackjm @joshid-ims Update is online, but not yet released. You can use the dev tool to test. If it looks good, I'll release.

Hi @cusackjm is this something you can test in dev? I believe there's a question in the updated M2 that we recently delivered that you could use to test.  

We need this confirmed fixed and released in order to complete our testing of the COVID-19 survey. Thanks!

**Comment by cusackjm** [comment] 2023-07-19 13:12
confirmed fix in module 2

**Comment by huip-ims** [comment] 2023-07-19 14:42
@danielruss Daniel - has this fix been released? When I just tested this in the renderer by adding the text in the text box without selecting the radio button, the text is stored correctly, but '55' is stored for the radio button Other option.

**Comment by huip-ims** [comment] 2023-07-19 14:47
@danielruss Nevermind, the renderer seems to be working correctly now.

**Comment by guinevere83** [comment] 2023-07-20 18:58
This has passed internal testing and will be delivered soon.

**Comment by cusackjm** [comment] 2023-07-24 18:55
confirmed fixed in dev testing 7/24/2023

**Closed by cusackjm** 2023-07-24 18:55 UTC
Labels: Awaiting Redelivery, COVID-19 Survey
