### ISSUE TITLE
CIGARLIFEA-H not seeing questions when "Never" responded at CIGAR3

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#127] opened 2022-06-02 22:34 UTC
CIGAR1 = 3 "100 or more"
CIGAR2 = 35
CIGAR3 = 44 "Never smoked on a regular basis"
CIGAR4 = 3 "Yes, everyday"
CIGAR9A = 2
CIGAR10 = 0 "Cigar", 1 "Cigarillo", 2 "Little filtered cigar"

Based on the specs document I should see CIGARLIFEA-H based on these responses:
![Screen Shot 2022-06-02 at 6 22 52 PM](https://user-images.githubusercontent.com/83971268/171748185-4c77bf36-15d4-441f-bad5-5acf63353077.png)

In the PWA, I am going from CIGAR10 - CHEW1

Spoke with @naiyume, we think the issue is that response 44 - Never in CIGAR3 doesn't allow the CIGARLIFE questions to establish a minimum age.  

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/83971268/171748470-dd79503f-99e0-496a-9ed1-ed77a69278ea.png)

Possible solution (@cusackjm - what do you think of this?):
When 44 is selected at CIGAR3, pull minimum age for CIGARLIFE from CIGAR2

I will work on checking to see if this is true for the other tobacco products.

**Comment by cusackjm** [comment] 2022-06-03 13:01
@boyd-mj this is a high priority issue

**Comment by joshid-ims** [comment] 2022-06-03 13:34
@cusackjm This is going to happen for all products as we have used the age started using product regularly for all of them. So this will be a code change for all products. This will take some time for coding and the whole module will need to be tested thoroughly. 

By when should this be done?

**Comment by cusackjm** [comment] 2022-06-03 14:07
@joshid-ims this is a low priority issue and will be revisited after the initial launch

**Comment by danielruss** [comment] 2022-06-08 15:08
no mixing off old and new functions.  BUT remember we are using mathjs to make life easier....

valueOrDefault("CIG3_AGE","CIG2",1)>= 0  (note: this is always true)
valueOrDefault("CIG3_AGE","CIG2",0) < 0

**Comment by joshid-ims** [comment] 2022-06-08 15:13
Sorry, not sure how I would use that here in example I gave.

**Comment by danielruss** [comment] 2022-06-08 15:13
I'll make an example...

**Comment by danielruss** [comment] 2022-06-08 15:32
```
[Q1]
Pick a positive number: |__|__|min=0|

[Q1A,displayif=doesNotExist("Q1")]
You chose not to give a number.  Lets try this again..

Please pick a positive number: |__|__|min=0|

[Q2]
Pick another positive number: |__|__|min=0|

[Q3]

Lets see this work:

Q1: {$Q1}     OR   Q1a: {$Q1A}
Q2: {$Q2}

|displayif=valueOrDefault("Q1","Q1A",-1) > valueOrDefault("Q2",-1)|Q1 is greater than Q2|
|displayif=valueOrDefault("Q1","Q1A",-1) < valueOrDefault("Q2",-1)|Q1 is less than Q2|
|displayif=valueOrDefault("Q1","Q1A",-1) == valueOrDefault("Q2",-1) and valueOrDefault("Q2",-1)>=0|Q1 is equal to Q2|

[END] Thank you for playing
```

**Comment by joshid-ims** [comment] 2022-06-08 15:35
Ok, thanks. Let me try in my scenario.

**Comment by joshid-ims** [comment] 2022-06-13 18:32
@danielruss, did you get a chance to look into this?

**Comment by danielruss** [comment] 2022-06-13 19:42
You don't check that TOBACCO==0. CIGLIFEA should not be be displayed.    Let me try with cigarettes.

**Comment by danielruss** [comment] 2022-06-13 20:26
I think this is logic.  Please double check...
```
(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==0) and  (valueOrDefault(AGE,age,100)-2 > 0) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 17)
```

**Comment by danielruss** [comment] 2022-06-13 20:35
I think the logic is wrong.  I think 7B should equal 1 not 0, and 8C should equal 1 not 0.

**Comment by danielruss** [comment] 2022-06-13 20:44
@FrogGirl1123  There is unnecessary repeated logic in cigarette/cigar/.... logic

```
[CIG7B?]/[CIG8C] During that time, did you ever smoke cigarettes <b>every day</b>?
(0) No ->  CIG7C/CIG8D
(1) Yes ->  CIG9A
< #NR -> CIG7C>
[CIG7C?]/CIG8D During that time, how many days (1 to 30) did you smoke cigarettes in a usual month?

#Days smoked in usual month |__|__|min=1 max=30|< -> CIG9A>
```

This will lead to unneeded extra variables, and extra complexity checking the values.   Can we please discuss with the questionnaire content team ways to refactor the questions?

**Comment by joshid-ims** [comment] 2022-06-14 16:49
@cusackjm can you please confirm what Daniel is saying is correct for 7B and 8C? If so, please make the change in the Word document. Then I will try the code he is suggesting.

**Comment by danielruss** [comment] 2022-06-14 16:52
@joshid-ims  My suggestion would change the ordering of the questions.  This would need approval from people at the PI level (Neal possibly?)

**Comment by danielruss** [comment] 2022-06-14 18:17
The same pattern is in CIGARS and the other smoking forms.

**Comment by cusackjm** [comment] 2022-06-14 20:44
@danielruss @joshid-ims Neal would like the following changes implemented. Let me know that these make sense on your end and I will update the questionnaire documents.

1. Update the CIGARLIFE skip logic from: 
"IF (CIGAR1 = 3 AND CIGAR4 = 3) OR (CIGAR1 = 3 AND CIGAR7B = **0**) OR(CIGAR1 = 3 AND CIGAR8C = **0**), GO TO CIGARLIFEA IF CIGAR3 **IS NULL**, GO TO CHEW1ELSE, GO TO CHEW1 (I.E. CIGAR1 = 2, GO TO CHEW1)"
to
"IF (CIGAR1 = 3 AND CIGAR4 = 3) OR (CIGAR1 = 3 AND CIGAR7B = **1**) OR(CIGAR1 = 3 AND CIGAR8C = **1**), GO TO CIGARLIFEA IF CIGAR3**= 44 "Never" OR Non-response**, GO TO CHEW1ELSE, GO TO CHEW1 (I.E. CIGAR1 = 2, GO TO CHEW1)

2. Delete the duplicate questions, as shown in the screenshot in my previous post

These changes will apply to all TOBACCO and MARIJUANA products

**Comment by danielruss** [comment] 2022-06-15 19:06
```
[CIGLIFEA?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 0) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 17)]

On days that you smoked when you were age|displayif=valueOrDefault("CIG3_AGE",1)>valueOrDefault("CIG2",1)|{$CIG3_AGE}||displayif=valueOrDefault("CIG3_AGE",1)<valueOrDefault("CIG2",1)|{$CIG2}||displayif=noneExist("CIG3_AGE","CIG2")|0|to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,17),17))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,17),17))|17||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,17)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,17)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),17))|17|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 18-24
[CIGLIFEB?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 18) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 24)]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),18)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),18)|18| to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,24),24))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,24),24))|24||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,24)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,24)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),24))|24|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 25-29
[CIGLIFEC?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 25) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 29)]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),25)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),25)|25| to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,29),29))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,29),29))|29||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,29)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,29)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),29))|29|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 30-39
[CIGLIFED?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 30) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 39)]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),30)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),30)|30| to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,39),39))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,39),39))|39||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,39)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,39)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),39))|39|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 40-49
[CIGLIFEE?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 40) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 49)]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),40)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),40)|40| to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,49),49))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,49),49))|49||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,49)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,49)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),49))|49|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 50-59
[CIGLIFEF?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 50) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 59)]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),50)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),50)|50| to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,59),59))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,59),59))|59||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,59)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,59)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),59))|59|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 60-69
[CIGLIFEG?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 60) and (valueOrDefault("CIG3_AGE","CIG2",18) <= 69)]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),60)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),60)|60| to |displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),lessThan(isDefined(CIG8,69),69))|{$CIG8}||displayif=and(and(equals(CIG8C,0),doesNotEqual(isDefined(CIG8,-1),-1)),greaterThanOrEqual(isDefined(CIG8,69),69))|69||displayif=and(doesNotEqual(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(AGE,69)))|{$AGE}||displayif=and(equals(isDefined(AGE,-1),-1),and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),lessThanOrEqual(age,69)))|{$u:age}||displayif=and(or(doesNotEqual(CIG8C,0),equals(isDefined(CIG8,-1),-1)),greaterThan(isDefined(AGE,age),69))|69|, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|

// 70+
[CIGLIFEH?,displayif=(_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG7B")==1 or _value("CIG8C")==1) and  (valueOrDefault("AGE","age",100)-2 > 70) ]
On days that you smoked when you were age |displayif=greaterThanOrEqual(isDefined(CIG3_AGE,-1),70)|{$CIG3_AGE}||displayif=lessThan(isDefined(CIG3_AGE,-1),70)|70| or older, about how many cigarettes did you smoke <b>per day</b>?
#CIGARETTES PER DAY |__|__|min=1 max=99|
```

renders appropriately for me + the logic appears correct

**Comment by joshid-ims** [comment] 2022-06-15 19:52
No, that is not working. One it is not recording CIG2 = 25 that I entered and the logic is wrong. I had only selected Tobacco =0. 

![image](https://user-images.githubusercontent.com/64986739/173915072-7e44b0af-81db-4dbf-896f-713e72781f68.png)

**Comment by joshid-ims** [comment] 2022-06-15 19:53
Not sure why it is going to CIGARLIFE.

**Comment by joshid-ims** [comment] 2022-06-15 20:00
Yes, I realized that but why should it go to CIGARLIFEC when I only selected Tobacco= 0 (only CIG questions should be displayed.).

CIG2 = 25 was entered. It is not being saved.

**Comment by danielruss** [comment] 2022-06-15 20:02
you finished the CIG questions.  The logic on CIGARLIFEC is wrong.

**Comment by danielruss** [comment] 2022-06-15 20:02
> You can check out [my test module](https://github.com/episphere/questionnaire/files/8912513/smoking.txt). However, I did not go past the CIGLIFE questions.

I did not got passed the CIGLIFE question

**Comment by danielruss** [comment] 2022-06-15 20:05
> CIG2 = 25 was entered. It is not being saved.

looking into this.

**Comment by danielruss** [comment] 2022-06-15 20:36
CIG2 is being saved now.

**Comment by joshid-ims** [comment] 2022-06-16 12:27
Did you make any change? Have you pushed it to production? Or do I need to change something? I still see CIG2 not being saved.

**Comment by cusackjm** [comment] 2022-06-16 12:47
> @danielruss @joshid-ims Neal would like the following changes implemented. **Let me know that these make sense on your end and I will update the questionnaire documents.**
> 
> 1. Update the CIGARLIFE skip logic from:
>    "IF (CIGAR1 = 3 AND CIGAR4 = 3) OR (CIGAR1 = 3 AND CIGAR7B = **0**) OR(CIGAR1 = 3 AND CIGAR8C = **0**), GO TO CIGARLIFEA IF CIGAR3 **IS NULL**, GO TO CHEW1ELSE, GO TO CHEW1 (I.E. CIGAR1 = 2, GO TO CHEW1)"
>    to
>    "IF (CIGAR1 = 3 AND CIGAR4 = 3) OR (CIGAR1 = 3 AND CIGAR7B = **1**) OR(CIGAR1 = 3 AND CIGAR8C = **1**), GO TO CIGARLIFEA IF CIGAR3**= 44 "Never" OR Non-response**, GO TO CHEW1ELSE, GO TO CHEW1 (I.E. CIGAR1 = 2, GO TO CHEW1)
> 2. Delete the duplicate questions, as shown in the screenshot in my previous post
> 
> These changes will apply to all TOBACCO and MARIJUANA products

@danielruss

**Comment by joshid-ims** [comment] 2022-06-17 14:25
CIG2 is still not storing for me. 

![image](https://user-images.githubusercontent.com/64986739/174317751-0fb2c06f-ea47-443e-8545-a4fe40dc131b.png)

**Comment by cusackjm** [comment] 2022-06-17 16:26
@boyd-mj @joshid-ims @huip-ims I updated the product sections and also noticed other errors in the PRODUCT4 responses and corresponding skip logic. Everything is marked in tracked changes. Let me know if you have any questions.

**Comment by FrogGirl1123** [comment] 2022-06-17 16:35
@joshid-ims Could your team please make the necessary updates to the transformed markup and redeliver?

**Comment by cusackjm** [comment] 2022-06-21 19:14
@joshid-ims yes that is correct

**Comment by joshid-ims** [comment] 2022-06-21 19:18
Ok, thanks!

**Comment by joshid-ims** [comment] 2022-06-24 17:58
@cusackjm, for X limit in LIFE questions, the current criteria is based only on CIG3 age. But now we are displaying the LIFE questions when CIG3 = 44. So should a criteria be added there using CIG2 age as well? If so, could you please update the Word document?

**Comment by cusackjm** [comment] 2022-06-24 18:14
@joshid-ims 
![image](https://user-images.githubusercontent.com/85582895/175618817-9bdc7629-2248-49f3-ac69-c1b73de83034.png)
We are not displaying life questions when cig3=44

**Comment by joshid-ims** [comment] 2022-06-24 18:17
From the very first comment in this issue:

When 44 is selected at CIGAR3, pull minimum age for CIGARLIFE from CIGAR2

**Comment by cusackjm** [comment] 2022-06-24 18:23
@joshid-ims that comment was not finalized or implemented in the qx docs. please follow the instructions in the document

**Comment by joshid-ims** [comment] 2022-06-27 17:51
Should '**IF CIG3 is NULL go to ECIG1**' be changed to '**If CIG3 is NULL or 44 go to ECIG1**'?

**Comment by guinevere83** [comment] 2022-06-27 17:58
As far as I can see, the document hasn't been updated to include any logic to skip the LIFE questions if CIG3 is 44. Are those changes pending or is the logic about NULL covering that? For NULL do we mean NR or 44 or just NR?

**Comment by cusackjm** [comment] 2022-06-27 18:32
@joshid-ims @guinevere83 I can further specify that null refers to non-response and 44 never in the documents. 

I will update this comment when Im done making the changes

**Comment by danielruss** [comment] 2022-06-30 13:50
You have one too many closing parentheses.

displayif=exists("CIG3_AGE") and ((_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG8C")==1)) and (valueOrDefault("AGE","age",100)-2 > 0))

```
exists("CIG3_AGE") and
      ^----------^
((_value("CIG1")==3) and (_value("CIG4")==3 or _value("CIG8C")==1)) 
^^======^++++++^===^-----^======^++++++^=============^+++++++^===^^
 and (valueOrDefault("AGE","age",100)-2 > 0))
     ^--------------^===============^------^X
```
Where `-` is in set of parentheses of depth 1, `=` is depth 2,  `+` is depth 3.

**Comment by guinevere83** [comment] 2022-07-01 18:06
Hi there, for the LIFE questions, we have specifications like so:

![image](https://user-images.githubusercontent.com/75336502/176947522-1266c764-8fcb-4e75-acb1-92e8cbf961a1.png)

So in these situations if CIG3 is greater than Y/17, are we expecting to skip this question? Otherwise, the logic as written causes situations like this:

![image](https://user-images.githubusercontent.com/75336502/176947614-8a2a584e-c220-40e0-b516-aa8eb0ef1413.png)

**Comment by joshid-ims** [comment] 2022-07-05 18:49
This is the case when CIG3_AGE is 73 and Current age is 75.

**Comment by cusackjm** [comment] 2022-07-06 18:47
@joshid-ims I checked the archive and it looks like some jargon got lost at some point. To avoid that from happening, we need a display check so that participants only see age ranges that they were everyday smokers in. Does it make sense to add the following display statement

"DISPLAY ONLY QUESTIONS THAT INCLUDE AT LEAST 1 AGE (CIG3_AGE or AGE) THAT FALLS BETWEEN X AND Y."

_For example:_ 
If CIG3_AGE= 33 and AGE= 63
CIGLIFEA, CIGLIFEB, CIGLIFEC are skipped
CIGLIFED, CIGLIFEE, CIGLIFEF, CIGLIFEG are displayed
CIFLIFEH is skipped

**Comment by joshid-ims** [comment] 2022-07-07 19:51
@danielruss this code is working when only AGE is defined or when age and AGE both are defined. But it is giving error when only age is defined. What could be the issue?

[CIGLIFEA?,displayif=exists("CIG3_AGE") and (_value("CIG1")==3 and (_value("CIG4")==3 or _value("CIG8C")==1)) and valueOrDefault("AGE","age",100)-2 > 0 and (_value("AGE")<=17 or _value("age")<=17 or _value("CIG3_AGE")<=17)]

@FrogGirl1123

**Comment by danielruss** [comment] 2022-07-08 13:22
@joshid-ims   The reason that _value has an underscore in front of it is because I never intended anyone to use it.  I wanted people to use valueOrDefault.  I would recommend never using _value but using valueOrDefault.  

So in this case: replace `_value("AGE")<=17` with `valueOrDefault("AGE",100) <= 17`.  You need to think about how to set the default.  In this case, you want the default to be GREATER than 17.   In this example, you may want to use `valueOrDefault("AGE","age",100) <= 17` as this truly reflects the meaning of "AGE" and "age".

CASE 1:  `valueOrDefault("AGE",100) <= 17` or `valueOrDefault("age",100) <= 17`... assume that the user said their age is 16 in the user profile (which is unrealistic for CONNECT, why are we even checking is a better question), but in module 1 they correct it to AGE=50.  This case would be TRUE because age<17.

CASE 2:   `valueOrDefault("AGE","age",100) <= 17` If the same situation plays out, we get the value of `AGE` which is 50, then check that it is less than 17, which is FALSE.  Notice that `age` never enters the equation.  Of course if the user said `age`=16 and never corrected it in module 1, then the `AGE` is not defined, so `valueOrDefault` returns 16 and the case returns TRUE. 

I think CASE 2 represents what the module authors really want.  @FrogGirl1123  what do you think?

**Comment by danielruss** [comment] 2022-07-08 13:25
@FrogGirl1123 Can someone check the logic of this question.  We should not be checking that the age is less than 17.  It is not a realistic situation.  If age is less than 17, someone verified an invalid participant.

**Comment by joshid-ims** [comment] 2022-07-08 20:06
@cusackjm can we please have this in the document (what you had said in the issue)?

"DISPLAY ONLY QUESTIONS THAT INCLUDE AT LEAST 1 AGE (CIG3_AGE or AGE) THAT FALLS BETWEEN X AND Y."
For example:
If CIG3_AGE= 33 and AGE= 63
CIGLIFEA, CIGLIFEB, CIGLIFEC are skipped
CIGLIFED, CIGLIFEE, CIGLIFEF, CIGLIFEG are displayed
CIFLIFEH is skipped

Also, we noticed that we need to add condition for not displaying questions based on CIG8 age.

**Comment by cusackjm** [comment] 2022-07-11 14:15
@joshid-ims, right now it is: (using CIGLIFEC as example)

Age [X / 25] to age [Y / 29]|__|__| #CIGARETTES PER DAY [X= [VALUE AT CIG3 OR 25, WHICHEVER IS HIGHEST VALUE] Y= [IF CIG4= 3 THEN 29 OR CURRENT AGE, WHICHEVER IS LOWEST VALUE] OR [IF CIG8C=1 THEN SET TO VALUE AT CIG8]]

For the related CIG8 revision, does the following work:
Age [X / 25] to age [Y / 29]|__|__| #CIGARETTES PER DAY [X= [VALUE AT CIG3 OR 25, WHICHEVER IS HIGHEST VALUE] Y= [IF CIG4= 3 THEN 29 OR CURRENT AGE, WHICHEVER IS LOWEST VALUE] OR [IF CIG8C=1 THEN SET TO VALUE AT CIG8 **OR CURRENT AGE, WHICHEVER IS LOWEST VALUE**]]

**Comment by joshid-ims** [comment] 2022-07-11 14:47
We need a condition to decide whether to display that LIFE question or not based on CIG8. 

for ex: when AGE = 50, CIG3_AGE = 28, CIG8 = 32. Currently the condition to display question is:

IF (CIG1 = 3 AND CIG4 = 3) OR  (CIG1 = 3 AND CIG8C = 1), GO TO CIGLIFEA. 

No mention about CIG8 age. So LIFE questions ask about product use per day for ages after they stopped smoking as well.

**Comment by joshid-ims** [comment] 2022-07-11 16:58
@cusackjm I guess that depends what you guys want the logic to be.

**Comment by joshid-ims** [comment] 2022-07-12 12:40
@FrogGirl1123 @cusackjm I am waiting for updates in Box to start coding accordingly.

**Comment by cusackjm** [comment] 2022-07-12 17:37
@joshid-ims questionnaire documents are updated

**Comment by cusackjm** [comment] 2022-07-12 18:14
@joshid-ims I will and an else statement now to indicate the participant should not see the LIFE questions and go to the next product

**Comment by cusackjm** [comment] 2022-07-14 15:38
@joshid-ims @guinevere83 we do not want to include CIG9B/CIG5 in the skip logic. Below is my draft logic. Let me know what you think and once confirmed I will edit the qx documents.

IF (CIG1 = 3 AND CIG4 = 3) DISPLAY ONLY QUESTIONS THAT INCLUDE AT LEAST ONE AGE (CIG3_AGE AND AGE) THAT FALLS BETWEEN X AND Y. IF CIG3 = 44 (NEVER) OR NON-RESPONSE, GO TO ECIG1.
IF (CIG1 = 3 AND CIG8C = 1) DISPLAY ONLY QUESTIONS THAT INCLUDE AT LEAST ONE AGE (CIG3_AGE AND CIG8_AGE) THAT FALLS BETWEEN X AND Y. IF (CIG3= 44 (NEVER) OR NON-RESPONSE) OR (CIG8= NON-RESPONSE), GO TO ECIG1.
ELSE, GO TO ECIG1

**Comment by guinevere83** [comment] 2022-07-14 16:02
Alright, just to confirm, we're aiming to not display life questions when CIG5 is 0, 1, or NR, correct? One can get to CIG8C via when CIG5 = 1 but that would route the participant to CIG7A then CIG8C. In that case, CIG8 would be non-response since it wouldn't be active. If all of that is OK, then the only thing I'd add is this:

IF (CIG1 = 3 AND CIG4 = 3) DISPLAY ONLY QUESTIONS THAT INCLUDE AT LEAST ONE AGE **(BETWEEN** CIG3_AGE AND AGE) THAT FALLS BETWEEN X AND Y. IF CIG3 = 44 (NEVER) OR NON-RESPONSE, GO TO ECIG1.
IF (CIG1 = 3 AND CIG8C = 1) DISPLAY ONLY QUESTIONS THAT INCLUDE AT LEAST ONE AGE **(BETWEEN**CIG3_AGE AND CIG8_AGE) THAT FALLS BETWEEN X AND Y. IF (CIG3= 44 (NEVER) OR NON-RESPONSE) OR (CIG8= NON-RESPONSE), GO TO ECIG1.
ELSE, GO TO ECIG1

That way it's extra clear that we're doing the range between the two ages and not just the two values.

**Comment by cusackjm** [comment] 2022-07-14 17:48
@guinevere83 yes that is correct. I will update the qx documents with what you wrote above now

**Comment by guinevere83** [comment] 2022-07-19 15:23
This has passed internal testing and will be ready to deliver.

**Comment by cusackjm** [comment] 2022-07-25 18:39
skip logic is fixed in 7/25 testing. I created separate issues #154 and #155 to track changes part of this issue that were not fixed.

**Closed by cusackjm** 2022-07-25 18:39 UTC
Labels: Mod3, RE-TEST THE FIX, MARKUP ISSUE
